name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string
      commit-hash:
        description: 'Commit'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ inputs.commit-hash }}

    - name: Retrieve dependencies
      run: |
        wget --quiet --output-document=Managed.zip ${{ secrets.DependenciesUrl }}/Managed.zip
        unzip Managed.zip -d .
        sha256sum ./Managed/*
        mkdir C2VM.TrafficLightsEnhancement
        mkdir C2VM.CommonLibraries

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build BepInEx 6 version
      run: |
        dotnet build --configuration Release --property:BepInExVersion=6
        cp ./TrafficLightsEnhancement/bin/Release/net46/C2VM.TrafficLightsEnhancement.dll ./C2VM.TrafficLightsEnhancement/
        cp ./TrafficLightsEnhancement/bin/Release/net46/C2VM.CommonLibraries.LaneSystem.dll ./C2VM.CommonLibraries/
        zip -r ./C2VM.TrafficLightsEnhancement-BepInEx6.zip ./C2VM.TrafficLightsEnhancement/ ./C2VM.CommonLibraries/
        rm -rf ./C2VM.TrafficLightsEnhancement/*
        rm -rf ./C2VM.CommonLibraries/*

    - name: Build BepInEx 5 version
      run: |
        dotnet build --configuration Release --property:BepInExVersion=5
        cp ./TrafficLightsEnhancement/bin/Release/net46/C2VM.TrafficLightsEnhancement.dll ./C2VM.TrafficLightsEnhancement/
        cp ./TrafficLightsEnhancement/bin/Release/net46/C2VM.CommonLibraries.LaneSystem.dll ./C2VM.CommonLibraries/
        zip -r ./C2VM.TrafficLightsEnhancement-BepInEx5.zip ./C2VM.TrafficLightsEnhancement/ ./C2VM.CommonLibraries/
        rm -rf ./C2VM.TrafficLightsEnhancement/*
        rm -rf ./C2VM.CommonLibraries/*

    - name: Create release
      id: create-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sha256sum C2VM.TrafficLightsEnhancement-*.zip
        gh release create ${{ inputs.tag }} C2VM.TrafficLightsEnhancement-BepInEx5.zip C2VM.TrafficLightsEnhancement-BepInEx6.zip